services:
  notification-microservice:
    image: notification-microservice:latest
    container_name: notification-microservice
    volumes:
      - ./:/var/www/html
    networks:
      - project-network
    depends_on:
      - database
      - database-testing
      - rabbitmq
  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - project-network
  database:
    image: mariadb:11.7
    container_name: database
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notification
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - project-network
  database-testing:
    image: mariadb:11.7
    container_name: database-testing
    volumes:
      - database-testing-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notification_test
      MYSQL_USER: db_user_test
      MYSQL_PASSWORD: db_password_test
    networks:
      - project-network

volumes:
  database-volume:
    driver: local
  database-testing-volume:
    driver: local

networks:
  project-network:
    name: project-network
    driver: bridge